smsapp/app/urls.py
from django.urls import path

from .views import contact_view, monosms, multidifusionsms, whtasappdiffusionMuliple, whtasapp, dashbordsms, enregistrer, voir


app_name = 'emails'
urlpatterns = [
    path('create', contact_view, name='create'),
    path('enregistrer/client/', enregistrer, name='client'),
    path('voir/client/', voir, name='clients'),
    path('sms', monosms, name='sms'),
    path('diffusion/', multidifusionsms, name='multififusion'),
    path('whatsapp/', whtasapp, name='whatsapp'),
    path('diffusion-multiple/', whtasappdiffusionMuliple, name='whatdiffusion'),
    path('dashbord/', dashbordsms, name='dashbord')

]

smsapp/smsapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home, us

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('dashbord/', home, name='home'),
                  path('', include('app.urls')),
                  path('account/', include('account.urls')),
                  path('', us, name='us')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smsapp/app/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from twilio.rest import Client


class Entreprise(models.Model):
    telephone = PhoneNumberField()
    email = models.EmailField()
    name = models.CharField(max_length=45)

    def __str__(self):
        return str(self.telephone)


class ClientBoxs(models.Model):
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(max_length=100)
    telephone = PhoneNumberField()
    address = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.telephone)
    class Meta:
        ordering = ['-created_at']


class Messages(models.Model):
    recipient = models.ForeignKey(ClientBoxs, on_delete=models.CASCADE)
    sender = models.ForeignKey(Entreprise, on_delete=models.CASCADE)
    corps = models.TextField(max_length=160)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.corps

    def save(self, *args, **kwargs):
        if len(self.corps) < 160:
            account_sid = 'ACef63632b0ba2a47909195de3b18c6d65'
            auth_token = 'd84211952960f5b6780aac91474cba2e'
            client = Client(account_sid, auth_token)

            message = client.messages.create(
                body=f"{self.corps}",
                from_=f'{self.sender.telephone}',
                to=f'+{self.recipient.telephone}'
            )
            print(message)
        else:
            return None

        super().save()


class MessagesDiffusion(models.Model):
    recipient = models.ManyToManyField(ClientBoxs)
    sender = models.ForeignKey(Entreprise, on_delete=models.CASCADE)
    corps = models.TextField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.corps

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.recipient.count() <= 100:
            account_sid = 'ACef63632b0ba2a47909195de3b18c6d65'
            auth_token = 'd84211952960f5b6780aac91474cba2e'
            client = Client(account_sid, auth_token)

            for recipient in self.recipient.all():
                try:
                    message = client.messages.create(
                        body=f"{self.corps}",
                        from_=f'{self.sender.telephon}',
                        to=f'+{recipient.telephone}'
                    )
                    print(message)
                except Exception as e:
                    print(f"Erreur lors de l'envoi du message au destinataire {recipient}: {str(e)}")
        # Ne rien retourner si le nombre de destinataires est supérieur à 100


class MessagesWhatsapp(models.Model):
    recipient = models.ManyToManyField(ClientBoxs)
    sender = models.ForeignKey(Entreprise, on_delete=models.CASCADE)
    corps = models.TextField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.corps

    def save(self, *args, **kwargs):
        if self.recipient.count() <= 1000:
            account_sid = 'ACef63632b0ba2a47909195de3b18c6d65'
            auth_token = 'd84211952960f5b6780aac91474cba2e'
            client = Client(account_sid, auth_token)

            message = client.messages.create(
                body=f"{self.corps}",
                from_=f'{self.sender.telephone}',
                to=f'+{self.recipient.telephone}'
            )
            print(message)
        else:
            return None


class EmailCampagne(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=150, verbose_name='Objet')
    message = models.TextField(max_length=1000)
    attachement_piece = models.FileField(blank=True, null=True, verbose_name='piece jointe',
                                         upload_to='emailattachement')
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.subject

    def get_recipient_mail(self):
        emails = self.email.all()
        recipient_emails = [email.email for email in emails]
        return ", ".join(recipient_emails)

smsapp/templates/home/contact.html
{% extends 'base.html' %}
{% block content %}
<style>


.container {
  display: align-items;
  justify-content: center;
}
</style>

<br>
<br>


    <div class="container  mx-auto px-2">
        <div class="flex flex-wrap">
            <div class="flex items-center py-4 w-full">
                <div class="w-full">                    
                    <div class="">
                        <div class="flex flex-wrap justify-between">
                            <div class="items-center ">
                                <h1 class="font-semibold text-xl mb-1 block dark:text-slate-100">Email</h1>
                                <ol class="list-reset flex text-sm">
                                    <li><a href="#" class="text-gray-500">US Informatique</a></li>
                                    <li><span class="text-gray-500 mx-2">/</span></li>
                                    <li class="text-gray-500">Email</li>
                                    <li><span class="text-gray-500 mx-2">/</span></li>
                                    <li class="text-blue-600 hover:text-blue-700">Email</li>
                                </ol>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!--end container-->

   <div class="container mx-auto px-6 min-h-[calc(100vh-138px)]  relative pb-14 ">
    <div class="grid md:grid-cols-12 lg:grid-cols-12 xl:grid-cols-12 gap-4 mb-4  ">
        <div class="sm:col-span-12  md:col-span-12 lg:col-span-6 xl:col-span-8">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Envoi de mail</h4>
                </div><!--end card-header-->
                <div class="card-body">
                    <div id="error_message" class="bg-red-400 text-white mb-3 rounded ease-out duration-500">

                    </div>
                    <form action="{% url 'emails:create' %}" method="POST">
                                        {% csrf_token %}

                        <div class="mb-2 input_field">
                            <label for="id_subject" class="mb-2 label">Objet</label>
                            <input class="form-control" type="text" id="id_subject" name="subject" placeholder="Objet">
                        </div>
                        <div class="mb-2 input_field">
                            <label for="id_email" class="mb-2 label">Email</label>
                            <input class="form-control" type="email" id="id_email" name="email" placeholder="Email">
                        </div>

                        <div class="mb-2 input_field">
                            <label for="id_attachement_piece" class="mb-2 label">Pièce jointe</label>
                            <input class="form-control" type="file" id="id_attachement_piece" name="attachement_piece">
                        </div>

                        <div class="input_field mb-2">
                            <label for="id_message" class="mb-2 label">Message</label>
                            <textarea id="id_message" name="message" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-200 focus:ring-blue-500 focus:border-blue-500 dark:bg-slate-700 dark:border-slate-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Rédiger votre message ici...."></textarea>
                        </div>
                        <button type="submit" class="px-3 py-2 lg:px-4 bg-blue-500 text-white text-sm font-semibold rounded hover:bg-blue-600">Envoyé Maintenant</button>
                    </form>
                </div><!--end card-body-->
            </div> <!--end card-->
        </div><!--end col-->
    </div><!--end inner-grid-->
    <!-- footer -->
</div><!--end container-->

    {% endblock %}

smsapp/templates/home/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Message envoyé avec succes </p>

</body>
</html>