smsapp/app/urls.py
from django.urls import path

from .views import contact_view, monosms, multidifusionsms, whtasappdiffusionMuliple, whtasapp, dashbordsms, enregistrer, voir


app_name = 'emails'
urlpatterns = [
    path('create', contact_view, name='create'),
    path('enregistrer/client/', enregistrer, name='client'),
    path('voir/client/', voir, name='clients'),
    path('sms', monosms, name='sms'),
    path('diffusion/', multidifusionsms, name='multififusion'),
    path('whatsapp/', whtasapp, name='whatsapp'),
    path('diffusion-multiple/', whtasappdiffusionMuliple, name='whatdiffusion'),
    path('dashbord/', dashbordsms, name='dashbord')

]

smsapp/smsapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home, us

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('dashbord/', home, name='home'),
                  path('', include('app.urls')),
                  path('account/', include('account.urls')),
                  path('', us, name='us')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smsapp/templates/client/client.html
{% extends 'base.html' %}
{% block content %}
<style>


.container {
  display: align-items;
  justify-content: center;
}
</style>

<br>
<br>


    <div class="container  mx-auto px-2">
        <div class="flex flex-wrap">
            <div class="flex items-center py-4 w-full">
                <div class="w-full">
                    <div class="">
                        <div class="flex flex-wrap justify-between">
                            <div class="items-center ">
                                <h1 class="font-semibold text-xl mb-1 block dark:text-slate-100">Client</h1>
                                <ol class="list-reset flex text-sm">
                                    <li><a href="#" class="text-gray-500">US Informatique</a></li>
                                    <li><span class="text-gray-500 mx-2">/</span></li>
                                    <li class="text-gray-500">register</li>
                                    <li><span class="text-gray-500 mx-2">/</span></li>
                                    <li class="text-blue-600 hover:text-blue-700">Client</li>
                                </ol>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!--end container-->

   <div class="container mx-auto px-6 min-h-[calc(100vh-138px)]  relative pb-14 ">
    <div class="grid md:grid-cols-12 lg:grid-cols-12 xl:grid-cols-12 gap-4 mb-4  ">
        <div class="sm:col-span-12  md:col-span-12 lg:col-span-6 xl:col-span-8">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Enregistrer les clients</h4>
                </div><!--end card-header-->
                <div class="card-body">
                    <div id="error_message" class="bg-red-400 text-white mb-3 rounded ease-out duration-500">

                    </div>
                    <div class="mb-2 input_field">

                    <form  method="POST" action="{% url 'emails:client' %}">
                                        {% csrf_token %}
                             {{ client.as_p }}
                        <button type="submit" class="px-3 py-2 lg:px-4 bg-blue-500 text-white text-sm font-semibold rounded hover:bg-blue-600">Sauvegardé</button>

                    </form>
                </div><!--end card-body-->
            </div> <!--end card-->
        </div><!--end col-->
    </div><!--end inner-grid-->
    <!-- footer -->
</div><!--end container-->

    {% endblock %}


    <script src="{% static '/assets/libs/simplebar/simplebar.min.js' %]"></script>
    <script src="{% static '/assets/libs/simple-datatables/umd/simple-datatables.js' %]"></script>
    <script src="{% static '/assets/js/pages/datatable.init.js' %]"></script>>