smsapp/account/urls.py
from django.urls import path, include
from .views import register, connexion
from django.contrib.auth import views as auth_views


app_name = 'accounts'
urlpatterns = [
    path("login/", connexion, name='login'),
    path('register/',  register, name='register'),

]

smsapp/app/urls.py
from django.urls import path

from .views import contact_view, monosms, multidifusionsms, whtasappdiffusionMuliple, whtasapp, dashbordsms, enregistrer, voir


app_name = 'emails'
urlpatterns = [
    path('create', contact_view, name='create'),
    path('enregistrer/client/', enregistrer, name='client'),
    path('voir/client/', voir, name='clients'),
    path('sms', monosms, name='sms'),
    path('diffusion/', multidifusionsms, name='multififusion'),
    path('whatsapp/', whtasapp, name='whatsapp'),
    path('diffusion-multiple/', whtasappdiffusionMuliple, name='whatdiffusion'),
    path('dashbord/', dashbordsms, name='dashbord')

]

smsapp/smsapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home, us

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('dashbord/', home, name='home'),
                  path('', include('app.urls')),
                  path('account/', include('account.urls')),
                  path('', us, name='us')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smsapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8" />
   <title>{% block title %}{% endblock %}</title>
  <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta
      content="Tailwind Multipurpose Admin & Dashboard Template"
      name="description"
    />
    <meta content="" name="Mannatthemes" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="assets/images/favicon.ico" />


    <link rel="stylesheet" href="{% static '/assets/css/icons.css' %}" />
    <link rel="stylesheet" href="{% static '/assets/css/tailwind.css' %}" />

</head>

<body data-layout-mode="light" class="bg-gray-100 dark:bg-gray-900 bg-[url('https://mannatthemes.com/T-Wind/images/bg-body.png')] dark:bg-[url('https://mannatthemes.com/T-Wind/images/bg-body-2.png')]">


    <!-- leftbar-tab-menu -->
    <nav  class="border-gray-200 bg-gray-900 px-2.5 py-2.5 shadow-sm dark:bg-slate-800 sm:px-4 block print:hidden">
      <div class="container mx-0 flex max-w-full flex-wrap items-center lg:mx-auto">
        <div class="flex items-center">
          <a href="#" class="flex items-center outline-none">
            <img src="assets/images/logo-sm.png" alt="" class="h-6" />
            <img src="assets/images/logo.png" alt="" class="ml-2 hidden xl:block mt-1" />
          </a>
        </div>

        <div
          class="order-2 hidden w-full items-center justify-between md:order-1 md:ml-5 md:flex md:w-auto"
          id="mobile-menu-2"
        >
          <ul
            class="font-body mt-4 flex flex-col font-medium md:mt-0 md:flex-row md:text-sm md:font-medium space-x-0 md:space-x-4 lg:space-x-6 xl:space-x-8 navbar"
          >
            <li class="dropdown">
              <button
                id="navDashboardLink"
                data-dropdown-toggle="navDashboard"
              >
                <i class="ti ti-smart-home mr-1 pb-1 text-lg"></i>  <a href="{% url 'home' %}" >Dashboards</a>
              </button>
              <!-- Dropdown menu -->
            </li>
            <li class="dropdown">
              <button
                id="navAppsLink"
                data-dropdown-toggle="navApps"
                class="dropdown-toggle flex w-full items-center border-b border-gray-800 py-2 px-3 font-medium md:border-0 md:p-0"
              >
              <button
                id="navUIkitLink"
                data-dropdown-toggle="navUIkit"
                class="dropdown-toggle flex w-full items-center border-b border-gray-800 py-2 px-3 font-medium md:border-0 md:p-0"
              >
                <!--i class="ti ti-planet mr-1 pb-1 text-lg"></i> UI KIt
                <i class="ti ti-chevron-down ml-auto lg:ml-1"></i>
              </button>
              <!-- Dropdown menu -->
              <div
                id="navUIkit"
                class="dropdown-menu z-20 my-1 hidden w-full sm:left-0 sm:right-0 md:left-0 md:right-0 lg:left-0 lg:right-0 xl:left-auto xl:right-auto  xl:max-w-screen-lg list-none divide-y divide-gray-100 rounded bg-gray-800 md:bg-white text-base shadow dark:divide-gray-600 border border-slate-700 md:border-white dark:border-slate-700/50 dark:bg-gray-900
                bg-[url('https://mannatthemes.com/T-Wind/images/widgets/m-p2.png')] bg-no-repeat bg-right-bottom dropdown-menu"
              >
                <div class="grid grid-cols-12 gap-4 px-4 pb-4">
                  <div class="col-span-6 md:col-span-3">
                    <h5 class="font-medium text-base p-4  border-b border-dashed border-slate-500 dark:border-slate-600 md:border-slate-300 text-slate-300 dark:text-slate-500 md:text-slate-700">
                      <span class="w-8 h-8 rounded-md inline-flex justify-center items-center mr-1 bg-pink-500 bg-opacity-10">
                        <i class="ti ti-planet text-pink-500"></i>
                      </span>
                     <!--h5>UI Elements</h5-->

                  </div>
                  <div class="col-span-6 md:col-span-3">
                    <h5 class="font-medium text-base p-4  border-b border-dashed border-slate-500 dark:border-slate-600 md:border-slate-300 text-slate-300 dark:text-slate-500 md:text-slate-700">
                      <span class="w-8 h-8 rounded-md inline-flex justify-center items-center mr-1 bg-blue-500 bg-opacity-10">
                        <i class="ti ti-tent text-blue-500"></i>
                      </span>
                      Advanced UI</h5>

                  <div class="col-span-6 md:col-span-3">
                    <h5 class="font-medium text-base p-4  border-b border-dashed border-slate-500 dark:border-slate-600 md:border-slate-300 text-slate-300 dark:text-slate-500 md:text-slate-700">
                      <span class="w-8 h-8 rounded-md inline-flex justify-center items-center mr-1 bg-yellow-500 bg-opacity-10">
                        <i class="ti ti-file-report text-yellow-500"></i>
                      </span>
                      Forms</h5>

                    <div>
                      <h5 class="font-medium text-base p-4  border-b border-dashed border-slate-500 dark:border-slate-600 md:border-slate-300 text-slate-300 dark:text-slate-500 md:text-slate-700">
                        <span class="w-8 h-8 rounded-md inline-flex justify-center items-center mr-1 bg-orange-500 bg-opacity-10">
                          <i class="ti ti-box text-orange-500"></i>
                        </span>
                        Icons</h5>
                    </div>
                  </div>
                </div>
              </div>
            </li>
            <li class="dropdown">
              <button
                id="navPagesLink"
                data-dropdown-toggle="navPages"
                class="dropdown-toggle flex w-full items-center border-b border-gray-800 py-2 px-3 font-medium md:border-0 md:p-0"
              >
                <i class="ti ti-file-diff mr-1 pb-1 text-lg"></i> Application
                <i class="ti ti-chevron-down ml-auto lg:ml-1"></i>
              </button>
              <!-- Dropdown menu -->
              <div
                id="navPages"
                class="dropdown-menu z-10 my-1 hidden w-full list-none divide-y divide-gray-100 rounded bg-gray-800 md:bg-white text-base shadow dark:divide-gray-600 border border-slate-700 md:border-white dark:border-slate-700/50 dark:bg-gray-900 md:w-44 dropdown-menu"
              >
                <ul class="py-1">
                  <li>
                    <a href="{% url 'emails:sms' %}" class="nav-link  dark:hover:bg-slate-800/70">Sms</a>
                  </li>

                      <li>
                    <a href="{% url 'emails:multififusion' %}" class="nav-link  dark:hover:bg-slate-800/70">Sms Multiple</a>
                  </li>


                  <li>
                    <a href="{% url 'emails:whatsapp' %}" class="nav-link  dark:hover:bg-slate-800/70">Whatsapp</a>
                  </li>
                  <li>
                  <li>
                    <a href="{% url 'emails:whatdiffusion' %}" class="nav-link  dark:hover:bg-slate-800/70">Whatsapp Multiple</a>
                  </li>
                  <li>
                    <a href="{% url 'emails:create' %}" class="nav-link  dark:hover:bg-slate-800/70">Email</a>
                  </li>

                </ul>
              </div>
               <li class="dropdown">
              <button
                id="navPagesLink"
                data-dropdown-toggle="navPages"
                class="dropdown-toggle flex w-full items-center border-b border-gray-800 py-2 px-3 font-medium md:border-0 md:p-0"
              >
                <i class="ti ti-file-diff mr-1 pb-1 text-lg"></i> Accounts
                <i class="ti ti-chevron-down ml-auto lg:ml-1"></i>
              </button>
              <!-- Dropdown menu -->
              <div
                id="navPages"
                class="dropdown-menu z-10 my-1 hidden w-full list-none divide-y divide-gray-100 rounded bg-gray-800 md:bg-white text-base shadow dark:divide-gray-600 border border-slate-700 md:border-white dark:border-slate-700/50 dark:bg-gray-900 md:w-44 dropdown-menu"
              >
                <ul class="py-1">
                  <li>
                    <a href="{% url 'accounts:register' %}" class="nav-link  dark:hover:bg-slate-800/70">Créer un compte</a>
                  </li>
                   </li>

                      <li>
                    <a href="{% url 'us' %}" class="nav-link  dark:hover:bg-slate-800/70">Menu</a>
                  </li>

                      <li>
                    <a href="{% url 'accounts:login' %}" class="nav-link  dark:hover:bg-slate-800/70">Se Connecter</a>
                  </li>


                  <li>
                    <a href="{% url 'us' %}" class="nav-link  dark:hover:bg-slate-800/70">Deconnecter</a>
                  </li>
                  <li>
                </ul>
              </div>
      </div>
        <div class="order-1 ml-auto flex items-center md:order-2">
          <div class="relative mr-2 hidden lg:mr-4 lg:block">
            <div
              class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
              <i class="ti ti-search text-gray-400 z-10"></i>
            </div>
            <input
              type="text"
              id="email-adress-icon"
              class="block w-full rounded-lg border border-gray-700 bg-gray-900 p-2 pl-10 text-gray-300 outline-none focus:border-gray-700 focus:ring-gray-700 dark:bg-slate-800 sm:text-sm"
              placeholder="Search..."
            />
          </div>
          <div class="mr-2 lg:mr-4">
            <button id="toggle-theme" class="flex rounded-full md:mr-0 relative">
              <i class="ti ti-sun top-icon"></i>
            </button>
          </div>
            </div>
          </div>

          <button
            data-collapse-toggle="mobile-menu-2"
            type="button" id="toggle-menu"
            class="ml-1 inline-flex items-center rounded-lg text-sm text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-0 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600 md:hidden"
            aria-controls="mobile-menu-2"
            aria-expanded="false"
          >
            <span class="sr-only">Open main menu</span>
            <i class="ti ti-menu-2 h-6 w-6 text-lg leading-6"></i>
            <i class="ti ti-X hidden h-6 w-6 text-lg leading-6"></i>
          </button>
        </div>
      </div>
    </nav>

{% block content %} {% endblock %}

         <!-- footer -->
        <div class="absolute bottom-0 left-2 right-2 block print:hidden">
          <div class="container mx-auto">
            <!-- Footer Start -->
            <!-- end Footer -->
          </div>
        </div>


    </div><!--end container-->


    <script src="{% static '/assets/libs/simplebar/simplebar.min.js' %}"></script>
    <script src="{% static '/assets/libs/chart.js/chart.min.js' %}"></script>
    <script src="{% static '/assets/libs/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static '/assets/libs/echarts/echarts.min.js' %}"></script>
    <script src="{% static '/assets/js/pages/analytics-index.init.js' %}"></script>
    <script src="{% static '/assets/js/app.js' %}"></script>
     <script src="{% static '/assets/libs/simplebar/simplebar.min.js' %}"></script>
    <script src="{% static '/assets/libs/mobius1-selectr/selectr.min.js' %}"></script>
    <script src="{% static '/assets/libs/huebee/huebee.pkgd.min.js"></script>
    <script src="{% static '/assets/libs/vanillajs-datepicker/js/datepicker-full.min.js' %}"></script>
    <script src="{% static '/assets/libs/moment/moment.js' %}"></script>
    <script src="{% static '/assets/libs/imask/imask.min.js' %}"></script>
    <script src="{% static '/assets/js/pages/advanced.init.js' %}"></script>

    <script src="{% static '/assets/libs/simplebar/simplebar.min.js' %}"></script>
    <script src="{% static '/assets/libs/simple-datatables/umd/simple-datatables.js' %}"></script>
    <script src="{% static '/assets/js/pages/datatable.init.js' %}"></script>

</body>


<!-- Mirrored from mannatthemes.com/T-Wind/default/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 29 Jun 2023 11:48:20 GMT -->
</html>

smsapp/templates/baselogin.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{% block title  %} {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/iofrm-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/iofrm-theme13.css' %}">
</head>
<body>
<div class="img-holder">
                <div class="bg"></div>
                <div class="info-holder">
                    <h3>Bienvenue chez US Informatique</h3>
                    <p>Nous vous accompagnons dans l'univers des campagnes publliciatires<br><br>
                       Et il ne s'avait pas du tout que s"était possible et ils l'ont fait, alors pour quoi ne pas s'engager avec nous aussi dans l'univers de la messagerie</p>
                </div>
</div>
{% block content  %}{% endblock %}



<script src="{% static '/js/jquery.min.js' %}"></script>
<script src="{% static '/js/popper.min.js' %}"></script>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
<script src="{% static '/js/main.js' %}"></script>
</body>

</html>